@startuml
'https://plantuml.com/sequence-diagram

participant ":Parser" as Parser
participant ":ModuleList" as ML
participant ":Module" as Module
participant ":Print" as Print
[->Parser : CheckUserInput\n(userInput:String, moduleList:ModuleList)
activate Parser


loop until all modules are added
    Parser->ML: addModule()
    activate ML
        ML->Module: Module(moduleCode:String, modularCredits:String, year:String, semester:String)
        activate Module
        Module-->ML: newModule:Module
        deactivate Module
        ML-->Parser: addedModule:Module

    Parser->ML: getModuleListSize()
    ML-->Parser: moduleListSize:Int
    deactivate ML
    Parser->Print: printAddedModule(addedModule:Module, moduleListSize:Int)
    activate Print
    Print-->Parser:
    deactivate Print
end
Parser-->[
deactivate Parser

@enduml
