@startuml

participant ":Command" as Command
participant ":ModuleList" as ML
participant ":Module" as Mod
participant "<<class>>\nPrint" as Print

[->Command : deleteCommand\n(userCommands:String[],\n moduleList:ModuleList)
activate Command
Command->ML : deleteModule(moduleCode:String)
activate ML

loop until module found or list ends
    ML -> Mod : getModuleCode()
    activate Mod
    Mod --> ML : moduleCode:String
    deactivate Mod
end
    ML --> Command : deletedModule:Module
deactivate ML

alt module found
    Command -> Print : printDeletedModule(deletedModule:Module, numOfModules:int)
    activate Print
    Print --> Command
    deactivate Print
else module not found
Command -> Print : printNoDeletedModuleFound(moduleCode:String)
    activate Print
    Print --> Command
    deactivate Print

end

deactivate ML
Command-->[
deactivate Command

@enduml