@startuml
'https://plantuml.com/sequence-diagram

box findModuleByName
participant ":Duke" as ChatBot
participant ":Parser" as Parser
participant ":ModuleList" as ModuleList
participant ":Print" as Print

end box

[-> ChatBot : execute("run")
activate ChatBot

create Parser
ChatBot -> Parser : execute("parser()")
activate Parser
ChatBot -> Parser: CheckUserInput("find /name /CS2113T")


Parser -> ModuleList : findModuleByName("CS2113T")
activate ModuleList
return

ModuleList -> Print : printFoundModule("foundModules")
activate Print

Print -> Print : Message printed to stdout

return
return
return


@enduml