@startuml
!include style.puml

skinparam sequence {

ParticipantBackgroundColor DodgerBlue
LifeLineBackgroundColor DodgerBlue
}

Actor User as user USER_COLOR
Participant ":Parser" as parser LOGIC_COLOR
Participant ":ModuleList" as modulelist MODEL_COLOR
Participant ":Module" as module
Participant "<<class>>\n:Print" as print UI_COLOR
Participant ":Storage" as storage STORAGE_COLOR


user -[USER_COLOR]> parser : "add /CS2113T /4 /CORE /1 /1"
activate parser LOGIC_COLOR

parser -[LOGIC_COLOR]> modulelist : execute ("add /CS2113T /4 /CORE /1 /1")
activate modulelist MODEL_COLOR

modulelist -[LOGIC_COLOR]> module : addmodule(/CS2113T /4 /CORE /1 /1)
activate module


module --> modulelist :
deactivate module

modulelist --> parser :
deactivate modulelist

parser -> print : printAddedModule()
activate print UI_COLOR

print --> parser :
deactivate print

parser -> storage : saveModules(moduleList.getModuleList())
activate storage STORAGE_COLOR

storage -[STORAGE_COLOR]> storage : Save to File
activate storage STORAGE_COLOR

storage -[STORAGE_COLOR]-> storage
deactivate storage

storage --> parser
deactivate storage

parser--[LOGIC_COLOR]> user
deactivate parser
@enduml
