@startuml
'https://plantuml.com/class-diagram
hide circle

interface ModuleList


class ModuleList {
(-) listOfModules: ArrayList<Module>
--
(+) getModuleList(): ArrayList<Module>
(+) getModuleListSize(): int
(+) addModule(moduleCode: String, modularCredits: String, moduleType: String,
year: String, semester: String): Module
(+) findModuleByCode(keyword: String): ArrayList<Module>
(+) findModuleByType(type: String): ArrayList<Module>
(+) deleteModule(moduleCode: String): Module
(+) listModules(): void
(+) addModulesToLists(year: String, moduleListByYear: ArrayList<Module>,
moduleListSemOne: ArrayList<String>, moduleListSpecialTermOne: ArrayList<String>,
moduleListSemTwo: ArrayList<String>, moduleListSpecialTermTwo: ArrayList<String>): void
(+) listModulesByYear(year: String): void
(+) editModularCredits(moduleCode: String, newModularCredits: String): void
(+) editYear(moduleCode: String, newYear: String): void
(+) editYear(moduleCode: String , newYear: String): void
(+) editSemester(moduleCode: String, newSemester: String): void
(+) editModuleGrade(moduleCode: String, newGrade: String): void
(+) editModuleType(moduleCode: String, moduleType: String): void
(+) editModuleCode(oldModuleCode: String, newModuleCode: String): void
(+) addExistingModule(line: String): void
(+) checkIfTampered(moduleGrade: String, moduleCode: String, modularCredits: String,
moduleYear: String, String moduleSemester: String): void
(+) updateModuleGrade(moduleCode: String, moduleGrade: String, command: String): Module
(-) validateSetModuleGrade(module: Module, command: String): void
(+) calculateCAP(): void
(+) shouldCountModuleGrade(moduleGrade: String): boolean
(+) getGradeValue(moduleGrade: String): double
(+) trackModules(moduleList: ArrayList<Module>, moduleType: String, requiredMCs: int): void
}



@enduml